export const boughtItemsFilter = {
  limit: "100",
  ignoreDelivered: false,
  ignoreCanceled: false,
  ignoreLost: false,
  highPriority: null,
  createdDate: "",
  changedDateFrom: "",
  sortBy: "created",
  id: "",
  status: "",
  group1: "",
  project: "",
  machine: "",
  partnumber: "",
  definition: "",
  manufacturer: "",
  supplier: "",
}

export const boughtItemsFilterPresetAllOpen = {
  limit: "",
  ignoreDelivered: false,
  ignoreCanceled: false,
  ignoreLost: false,
  highPriority: null,
  createdDate: "",
  changedDateFrom: "",
  sortBy: "high_priority,project,supplier,manufacturer",
  id: "",
  status: "open",
  group1: "",
  project: "",
  machine: "",
  partnumber: "",
  definition: "",
  manufacturer: "",
  supplier: "",
}

export const boughtItemsFilterPresetAllRequested = {
  limit: "",
  ignoreDelivered: false,
  ignoreCanceled: false,
  ignoreLost: false,
  highPriority: null,
  createdDate: "",
  changedDateFrom: "",
  sortBy: "high_priority,project,supplier,manufacturer",
  id: "",
  status: "requested",
  group1: "",
  project: "",
  machine: "",
  partnumber: "",
  definition: "",
  manufacturer: "",
  supplier: "",
}

export const boughtItemsFilterPresetAllOrdered = {
  limit: "",
  ignoreDelivered: false,
  ignoreCanceled: false,
  ignoreLost: false,
  highPriority: null,
  createdDate: "",
  changedDateFrom: "",
  sortBy: "high_priority,project,supplier,manufacturer",
  id: "",
  status: "ordered",
  group1: "",
  project: "",
  machine: "",
  partnumber: "",
  definition: "",
  manufacturer: "",
  supplier: "",
}

export const boughtItemsFilterPresetAllActive = {
  limit: "",
  ignoreDelivered: true,
  ignoreCanceled: true,
  ignoreLost: true,
  highPriority: null,
  createdDate: "",
  changedDateFrom: "",
  sortBy: "high_priority,project,supplier,manufacturer",
  id: "",
  status: "",
  group1: "",
  project: "",
  machine: "",
  partnumber: "",
  definition: "",
  manufacturer: "",
  supplier: "",
}

export const boughtItemsFilterPresetAllPrioritized = {
  limit: "",
  ignoreDelivered: true,
  ignoreCanceled: true,
  ignoreLost: true,
  highPriority: true,
  createdDate: "",
  changedDateFrom: "",
  sortBy: "project,supplier,manufacturer",
  id: "",
  status: "",
  group1: "",
  project: "",
  machine: "",
  partnumber: "",
  definition: "",
  manufacturer: "",
  supplier: "",
}
